### ISSUE TITLE
How do i disable "New Window" in Chapter 2

### ISSUE THREAD

**Issue by diuming** [trozware/mos_book_code#1]
How do i disable `File` -> `New Window` in Chapter 2

![Screenshot 2024-08-11 at 6 34 39 PM](https://github.com/user-attachments/assets/7d7f22ca-3231-49a6-9cf2-42c23a320540)

**Comment by trozware** [comment]
Every SwiftUI app has a **...App.swift** file and that file dictates the scenes that the app can show.
For non-document apps, the initial scene is a `WindowGroup` which allows for multiple instances of the window. With this in place, SwiftUI automatically adds a **File** menu with **New Window**  and **Close** menu items.

if you want to restrict an app to showing a single window only, replace `WindowGroup` with `Window`.
The `Window` initializer requires a title and a unique `id`. My example looks like this:

```swift
import SwiftUI

@main
struct SingleWindowApp: App {
  var body: some Scene {
    Window("Single Window", id: "main") {
      ContentView()
    }
  }
}
```

This totally removes the **File** menu (although you can bring it back by adding other items to it) and means that closing the window quits the entire app.

If you wanted to leave the menu in place but disabled, you could replace that `CommandGroup` - you'll read about menus in Chapter 3.

While this is good to know, I recommend that you leave the **OnThisDay** app with `WindowGroup` for now, as you will read later how to manage multiple windows and how to store window specific settings.

Hope this answers your question.

Sarah
