### ISSUE TITLE
Chapter 8: Menu item not reflecting completed task's status while the menu is opened

### ISSUE THREAD

**Issue by aurrak-hws** [trozware/mos_book_code#3]
Since `Task` is modeled as a `struct` and has value-type semantics, each `TaskView` has a copy of its own `Task` instance.

Let's say if a task timer is completed while the status menu is opened, only the task instance within the `taskManager.task[taskIndex]` is being updated, but not the copy within `TaskView`. The end result is that the menu item doesn't correctly reflect the completed state until the next time the menu is re-opened.

```
    func stopRunningTask(at taskIndex: Int) {
        tasks[taskIndex].complete()
        timerState = .waiting
        ...
```

Is there any clever way of updating the `TaskView` without modeling the `Task` as a class?

**Comment by trozware** [comment]
The best solution I found (without converting `Task` to a class) is to check for a change in status when updating the visible menu items. The progress percent is a computed property, so it updates constantly but the status of the task does not.

In **MenuManager.swift**, change `updateMenuItems()` to this:

```swift
func updateMenuItems() {
  for item in statusMenu.items {
    if let view = item.view as? TaskView {

      if let task = view.task {
        // Look for this task and check if its status has changed.
        let outdatedTask = taskManager.tasks.first {
          $0.id == task.id && $0.status != task.status
        }
        // If so, update it in the TaskView
        if let outdatedTask {
          view.task = outdatedTask
        }
      }

      view.setNeedsDisplay(.infinite)
    }
  }
}
```

This adds a block to check the TaskView's task and see if it has a different status than its match in TaskManager. If so, replace it. now (if you're using notifications), you'll see the open menu update correctly. If using alerts, it's still better to close the menu before showing the alert.

**Comment by aurrak-hws** [comment]
That's a great suggestion. Thanks for the idea!
